=== sxs0905/jsonview3/jsonview3-core/src/main/resources/jsonview-configuration-3.0.xsd
<xs:schema xmlns="http://www.developframework.org/schema/jsonview3"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.developframework.org/schema/jsonview3"
	elementFormDefault="qualified">
	<xs:element name="jsonview-configuration">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="jsonview-package" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="jsonview" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:group ref="elementGroup"/>
									<xs:attribute name="id" type="xs:string" use="required" />
									<xs:attribute name="data" type="xs:string" />
									<xs:attribute name="for-class" type="xs:string"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="namespace" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="containerElementType">
		<xs:group ref="elementGroup"></xs:group>
		<xs:attributeGroup ref="attrGroupForElement"/>
		<xs:attribute name="for-class" type="xs:string"/>
	</xs:complexType>
	<xs:attributeGroup name="attrGroupForElement">
		<xs:attribute name="data" type="xs:string" use="required"/>
		<xs:attribute name="alias" type="xs:string"/>
		<xs:attribute name="null-hidden" type="xs:boolean" default="true"/>
	</xs:attributeGroup>
	<xs:group name="elementGroup">
		<xs:sequence>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="object">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="containerElementType">
								<xs:attribute name="type">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:enumeration value="virtual" />
											<xs:enumeration value="entity" />
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="array">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="containerElementType"/>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="property">
					<xs:complexType>
						<xs:attributeGroup ref="attrGroupForElement"/>
						<xs:attribute name="handler" type="xs:string"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="property-date">
					<xs:complexType>
						<xs:attributeGroup ref="attrGroupForElement"/>
						<xs:attribute name="pattern" type="xs:string"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="ignore-property">
					<xs:complexType>
						<xs:attribute name="data" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="import">
					<xs:complexType>
						<xs:attribute name="namespace" type="xs:string"/>
						<xs:attribute name="id" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:sequence>
	</xs:group>
</xs:schema>

=== sxs0905/jsonview3/jsonview-demo/src/main/resources/jsonview/jsonview-student.xml
<jsonview-configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.developframework.org/schema/jsonview3" 
	xsi:schemaLocation="
	http://www.developframework.org/schema/jsonview3 
	http://www.developframework.org/schema/jsonview3/jsonview-configuration-3.0.xsd">
	<jsonview-package namespace="jsonview-student">
		<jsonview id="student-detail-view" data="student">
			<import id="student-detail"/>
		</jsonview>
		
		<jsonview id="student-list-view">
			<array data="students">
				<import id="student-detail"/>
			</array>
		</jsonview>
		
		<jsonview id="student-detail" data="student">
			<property data="id"/>
			<property data="name"/>
			<property data="classId"/>
			<property-date data="birthday" pattern="yyyy-MM-dd"/>
		</jsonview>
	</jsonview-package>
</jsonview-configuration>

=== sxs0905/jsonview3/jsonview3-spring-support/src/test/resources/jsonview/jsonview-class.xml
<jsonview-configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.developframework.org/schema/jsonview3" 
	xsi:schemaLocation="
	http://www.developframework.org/schema/jsonview3 
	http://www.developframework.org/schema/jsonview3/jsonview-configuration-3.0.xsd">
	<jsonview-package namespace="jsonview-class">
		<!-- 班级详情 -->
		<jsonview id="class-detail">
			<property data="id"/>
			<property data="className"/>
			<mapping-object data="#students" source="id"  target="classId" alias="student" type="multiple">
				<!-- 引用学生详情视图 -->
				<import id="student-detail" namespace="jsonview-student"/>
			</mapping-object>
		</jsonview>
		<!-- 班级列表视图 -->
		<jsonview id="class-list-view">
			<array data="schoolClasses">
				<import id="class-detail"/>
			</array>
		</jsonview>
	</jsonview-package>
</jsonview-configuration>

=== sxs0905/jsonview3/jsonview3-spring-support/src/test/resources/jsonview/jsonview-demo.xml
<jsonview-configuration
	xmlns="http://www.developframework.org/schema/jsonview3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="
	http://www.developframework.org/schema/jsonview3 
	http://www.developframework.org/schema/jsonview3/jsonview-configuration-3.0.xsd">

	<jsonview-package namespace="jsonview-demo">

		<jsonview id="user-list">
			<array data="users">
				<property data="id" />
				<property data="name" />
				
				<link-object data="#favorites">
					<property data="item" />
				</link-object>
			</array>
		</jsonview>
		
		<jsonview id="user-detail" data="user" for-class="test.User">
			<property-date data="birthday" pattern="yyyy-MM-dd"/>
			<array data="likes" for-class="test.Like"/>
		</jsonview>
	</jsonview-package>
</jsonview-configuration>
